services:

  ################################ D A T A - B A S E S ################################

  fd-postgres:
    image: postgres:15-alpine
    container_name: fd-postgres
    environment:
      POSTGRES_DB: fd-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fd-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fd-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"

  fd-pgadmin:
    image: dpage/pgadmin4
    container_name: fd-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - fd-postgres

  ################################ B R O K E R S ################################

  fd-kafka:
    image: apache/kafka:3.7.0
    container_name: fd-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://fd-kafka:9093,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093' # Исправлено с 127.0.0.1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ################################ M I C R O - S E R V I C E S ################################

  fd-users-ms:
    build:
      context: .
      dockerfile: ./fd-users-ms/Dockerfile
    container_name: fd-users-ms
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081

      # Исправлено: имя хоста fd-postgres (соответствует названию сервиса выше) и база fd-db
      SPRING_DATASOURCE_URL: "jdbc:postgresql://fd-postgres:5432/fd-db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "secret"

      # Внутри Docker-сети микросервис общается с Kafka через внутренний порт 9093
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "fd-kafka:9093"

      SPRING_RABBITMQ_HOST: "fd-rabbitmq"
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: "admin"
      SPRING_RABBITMQ_PASSWORD: "secret"
    depends_on:
      - fd-postgres
      - fd-kafka
      - fd-rabbitmq

volumes:
  pgdata: